# Generated by Django 3.1 on 2020-11-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(blank=True, help_text='Required. Format: YYYY-MM-DD', null=True),
        ),
    ]
