# Generated by Django 3.1 on 2020-11-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201115_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='accounts/', width_field=300),
        ),
    ]
