# Generated by Django 3.1 on 2020-11-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201115_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('w', 'women'), ('m', 'man')], max_length=100, null=True),
        ),
    ]
