# Generated by Django 3.1 on 2020-11-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sendmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmessage',
            old_name='first_name',
            new_name='full_name',
        ),
    ]
